### ISSUE TITLE
Unread count for activity

### ISSUE THREAD

**Issue by psql** [jake/screenhole#59]

**Comment by getaclue00** [comment]
yeah so @jake want me to handle that via server side? 

- I can add an attribute to user, say something like `last_synced_at` and 
- simply update it every time user sends a `get` request to `/sup`
- and it follows that this way when UI make a `get` request using `/sup/any` we will simply check if there are any new notifications since `last_synced_at` time

Thoughts?

**Comment by jake** [comment]
yeah, that seems pretty solid! maybe `sup_last_requested_at`?

should we have the client actually make a GET request to an endpoint that updates that field, or should we handle it internally when requesting the sup request itself?

**Comment by getaclue00** [comment]
I think we should handle it all on the server personally that way its transparent to the user... but im open

**Comment by jake** [comment]
agreed!
